name: Create Release

on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Tag Name'
        required: true
      target:
        description: 'What to release'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        <publishFabric>- fabric</publishFabric>
        <publishForge>- forge</publishForge>
      changelog:
        description: 'Changelog'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup jdk 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: make gradle wrapper executable
        run: chmod +x ./gradlecw
      - name: build
        run: ./gradlecw build
      - name: Save Changelog
        run: echo "$LOG" > CHANGELOG.txt
        env:
          LOG: ${{ inputs.changelog }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ inputs.name }}
          tag_name: ${{ inputs.name }}
          body_path: CHANGELOG.txt
          generate_release_notes: true
          files: |
$autoworkflowfiles$
<autopublish>
<publishForge>
      - name: Publish-Forge-Curseforge
        if: inputs.target == 'forge' || inputs.target == 'all'
        uses: Kir-Antipov/mc-publish@v3.2
        with:
<curseforge>
          curseforge-id: $curseforgeid$
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}  
</curseforge>
          loaders: forge
          name: ${{inputs.name}} - Forge
          github-tag: ${{inputs.name}}
          version-type: beta
          files: '*Forge/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
      - name: Publish-Forge-Modrinth
        uses: Kir-Antipov/mc-publish@v3.2
        with:
<modrinth>
          modrinth-id: $modrinthid$
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
</modrinth>
          loaders: forge
          name: ${{inputs.name}} - Forge
          github-tag: ${{inputs.name}}
          files: '*Forge/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
</publishForge>
<publishFabric>
      - name: Publish-Fabric
        if: inputs.target == 'fabric' || inputs.target == 'all'
        uses: Kir-Antipov/mc-publish@v3.2
        with:
<modrinth>
          modrinth-id: $modrinthid$
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
</modrinth>
<curseforge>
          curseforge-id: $curseforgeid$
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}  
</curseforge>
          loaders: fabric
          name: ${{inputs.name}} - Fabric
          github-tag: ${{inputs.name}}
          files: '*Fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
</publishFabric>
</autopublish>